os:
  - linux
language: node_js
node_js:
  - 8
  - 10
  - 12
script:
  - npm run release
deploy:
  - provider: npm
    edge: true
    email: $NPM_EMAIL
    api_token: $NPM_API_TOKEN
    on:
      tags: true
  - provider: pages
    edge: true
    keep_history: false
    token: $GITHUB_TOKEN
    target_branch: gh-pages
    on:
      branch: master
after_success:
  - codecov